version: '2'
services:
  api_main:
    build: ./api
    volumes:
      - /app
    restart: always

  nginx_main:
    build: ./nginx
    ports:
      - "80:80"
    volumes_from:
      - api_main:rw
    restart: always